


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowCliente(object):
    def setupUi(self, MainWindowCliente):
        MainWindowCliente.setObjectName("MainWindowCliente")
        MainWindowCliente.resize(752, 664)
        MainWindowCliente.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindowCliente)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(80, 130, 631, 371))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 71, 81))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(270, 10, 71, 81))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(490, 10, 71, 81))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(490, 130, 71, 81))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(50, 120, 71, 81))
        self.label_6.setObjectName("label_6")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(270, 120, 71, 81))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(60, 270, 61, 71))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(190, 270, 71, 71))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(350, 270, 61, 71))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(490, 270, 61, 71))
        self.label_15.setObjectName("label_15")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 70, 161, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(208, 190, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 204, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(208, 190, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 204, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Harlow Solid Italic")
        font.setPointSize(18)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(200, 0, 161, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(206, 186, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 204, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 186, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 204, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_7.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Harlow Solid Italic")
        font.setPointSize(18)
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setTextFormat(QtCore.Qt.PlainText)
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 530, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Al Bayan")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(365, 24, 118, 24))
        self.timeEdit.setMaximumTime(QtCore.QTime(17, 0, 0))
        self.timeEdit.setMinimumTime(QtCore.QTime(8, 0, 0))
        self.timeEdit.setTime(QtCore.QTime(8, 0, 0))
        self.timeEdit.setObjectName("timeEdit")
        MainWindowCliente.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowCliente)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 752, 22))
        self.menubar.setObjectName("menubar")
        MainWindowCliente.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowCliente)
        self.statusbar.setObjectName("statusbar")
        MainWindowCliente.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowCliente)
        QtCore.QMetaObject.connectSlotsByName(MainWindowCliente)

    def retranslateUi(self, MainWindowCliente):
        _translate = QtCore.QCoreApplication.translate
        MainWindowCliente.setWindowTitle(_translate("MainWindowCliente", "Home"))
        self.label_2.setText(_translate("MainWindowCliente", "<html><head/><body><p><img src=\":/table/dining-table.png\"/></p></body></html>"))
        self.label_3.setText(_translate("MainWindowCliente", "<html><head/><body><p><img src=\":/table/dining-table.png\"/></p></body></html>"))
        self.label_4.setText(_translate("MainWindowCliente", "<html><head/><body><p><img src=\":/table/dining-table.png\"/></p></body></html>"))
        self.label_5.setText(_translate("MainWindowCliente", "<html><head/><body><p><img src=\":/table/dining-table.png\"/></p></body></html>"))
        self.label_6.setText(_translate("MainWindowCliente", "<html><head/><body><p><img src=\":/table/dining-table.png\"/></p></body></html>"))
        self.label_11.setText(_translate("MainWindowCliente", "<html><head/><body><p><img src=\":/table/dining-table.png\"/></p></body></html>"))
        self.label_12.setText(_translate("MainWindowCliente", "<html><head/><body><p><img src=\":/picnic/table.png\"/></p></body></html>"))
        self.label_13.setText(_translate("MainWindowCliente", "<html><head/><body><p><img src=\":/picnic/table.png\"/></p></body></html>"))
        self.label_14.setText(_translate("MainWindowCliente", "<html><head/><body><p><img src=\":/picnic/table.png\"/></p></body></html>"))
        self.label_15.setText(_translate("MainWindowCliente", "<html><head/><body><p><img src=\":/picnic/table.png\"/></p></body></html>"))
        self.label.setText(_translate("MainWindowCliente", "  Seleziona tavolo:"))
        self.label_7.setText(_translate("MainWindowCliente", "  Seleziona orario:"))
        self.pushButton.setText(_translate("MainWindowCliente", "Conferma"))
        self.timeEdit.setDisplayFormat(_translate("MainWindowCliente", "HH:00"))
import picnic_rc
import table_rc
